# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wavelength
email: ashwin.kannan@berkeley.edu
description: Wavelength
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akannan747.github.io" # the base hostname & protocol for your site
excerpt_separator: excerpt

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: akannan747
# twitter_username: andrewbanchich
# facebook_URL: andrewbanchich
# 500px_username: andrewbanchich
phone: 630-788-8850

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
